### ISSUE TITLE
[EASY LEVEL] - Check and fix README.md

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/frontend-modern-boilerplate#29]
For this `#hacktoberfest` event I am looking for someone who help me fixing my readme.md (if needed).

Feel free to open everything you want to grab the t-shirt (I will accept only useful pr)
_(please also support me ---> click on the :star: and I will love you more <3)_

---
FOLLOW THE **HOW TO CONTRIBUTE** PARAGRAPH FOR THE PULL REQUESTS

**Comment by bhadreshpsavani** [comment]
I can do this, Please assign me this issue

**Comment by ibbatta** [comment]
@bhadreshpsavani feel free to work on it :)
